### ISSUE TITLE
Checkpoints are doubled

### ISSUE THREAD

**Issue by andrew8712** [AfterShip/aftership-ios#4]
Checkpoints seem repeated twice:

    "<AftershipCheckpoint: self.createTime=2014-12-28 18:57:00 +0000, self.slug=dhl, self.checkpointTime=2014-12-28T00:00:00, self.city=(null), self.state=(null), self.countryCode=(null), self.countryName=LEEDS - UNITED KINGDOM, self.message=Shipment information received, self.tag=InfoReceived, self.zip=(null)>",
    "<AftershipCheckpoint: self.createTime=2014-12-30 14:40:32 +0000, self.slug=dhl, self.checkpointTime=2014-12-28T00:00:00, self.city=LEEDS, self.state=(null), self.countryCode=GBR, self.countryName=LEEDS - UNITED KINGDOM, self.message=Shipment information received, self.tag=InfoReceived, self.zip=(null)>",
    "<AftershipCheckpoint: self.createTime=2014-12-31 02:21:14 +0000, self.slug=dhl, self.checkpointTime=2014-12-30T23:46:55, self.city=(null), self.state=(null), self.countryCode=(null), self.countryName=GATWICK - UNITED KINGDOM, self.message=Processed at GATWICK - UNITED KINGDOM, self.tag=InTransit, self.zip=(null)>",
    "<AftershipCheckpoint: self.createTime=2014-12-31 02:41:02 +0000, self.slug=dhl, self.checkpointTime=2014-12-30T23:46:55, self.city=GATWICK, self.state=(null), self.countryCode=GBR, self.countryName=GATWICK - UNITED KINGDOM, self.message=Processed at GATWICK - UNITED KINGDOM, self.tag=InTransit, self.zip=(null)>",
    "<AftershipCheckpoint: self.createTime=2014-12-31 08:41:05 +0000, self.slug=dhl, self.checkpointTime=2014-12-31T06:37:22, self.city=GATWICK, self.state=(null), self.countryCode=GBR, self.countryName=GATWICK - UNITED KINGDOM, self.message=Departed Facility in GATWICK - UNITED KINGDOM, self.tag=InTransit, self.zip=(null)>",
    "<AftershipCheckpoint: self.createTime=2014-12-31 11:05:52 +0000, self.slug=dhl, self.checkpointTime=2014-12-31T06:37:22, self.city=(null), self.state=(null), self.countryCode=(null), self.countryName=GATWICK - UNITED KINGDOM, self.message=Departed Facility in GATWICK - UNITED KINGDOM, self.tag=InTransit, self.zip=(null)>",
    "<AftershipCheckpoint: self.createTime=2014-12-31 22:07:43 +0000, self.slug=dhl, self.checkpointTime=2014-12-31T19:15:44, self.city=DUBLIN, self.state=(null), self.countryCode=(null), self.countryName=DUBLIN - IRELAND, REPUBLIC OF, self.message=Arrived at Sort Facility DUBLIN - IRELAND, REPUBLIC OF, self.tag=InTransit, self.zip=(null)>",
    "<AftershipCheckpoint: self.createTime=2015-01-01 00:31:28 +0000, self.slug=dhl, self.checkpointTime=2014-12-31T19:15:44, self.city=(null), self.state=(null), self.countryCode=(null), self.countryName=DUBLIN - IRELAND, REPUBLIC OF, self.message=Arrived at Sort Facility DUBLIN -\nIRELAND, REPUBLIC OF, self.tag=InTransit, self.zip=(null)>",
    "<AftershipCheckpoint: self.createTime=2014-12-31 22:07:43 +0000, self.slug=dhl, self.checkpointTime=2014-12-31T19:31:00, self.city=DUBLIN, self.state=(null), self.countryCode=(null), self.countryName=DUBLIN - IRELAND, REPUBLIC OF, self.message=Transferred through DUBLIN - IRELAND, REPUBLIC OF, self.tag=InTransit, self.zip=(null)>",
    "<AftershipCheckpoint: self.createTime=2015-01-01 00:31:29 +0000, self.slug=dhl, self.checkpointTime=2014-12-31T19:31:00, self.city=(null), self.state=(null), self.countryCode=(null), self.countryName=DUBLIN - IRELAND, REPUBLIC OF, self.message=Transferred through DUBLIN - IRELAND,\nREPUBLIC OF, self.tag=InTransit, self.zip=(null)>",
    "<AftershipCheckpoint: self.createTime=2015-01-02 10:08:03 +0000, self.slug=dhl, self.checkpointTime=2015-01-02T09:35:00, self.city=SHANNON, self.state=(null), self.countryCode=(null), self.countryName=SHANNON - IRELAND, REPUBLIC OF, self.message=With delivery courier, self.tag=OutForDelivery, self.zip=(null)>",
    "<AftershipCheckpoint: self.createTime=2015-01-02 13:46:56 +0000, self.slug=dhl, self.checkpointTime=2015-01-02T09:35:00, self.city=(null), self.state=(null), self.countryCode=(null), self.countryName=SHANNON - IRELAND, REPUBLIC OF, self.message=With delivery courier, self.tag=OutForDelivery, self.zip=(null)>",
    "<AftershipCheckpoint: self.createTime=2015-01-02 11:08:04 +0000, self.slug=dhl, self.checkpointTime=2015-01-02T10:09:00, self.city=SHANNON, self.state=(null), self.countryCode=(null), self.countryName=SHANNON - IRELAND, REPUBLIC OF, self.message=Delivery attempted; recipient not home, self.tag=AttemptFail, self.zip=(null)>",
    "<AftershipCheckpoint: self.createTime=2015-01-02 13:46:57 +0000, self.slug=dhl, self.checkpointTime=2015-01-02T10:09:00, self.city=(null), self.state=(null), self.countryCode=(null), self.countryName=SHANNON - IRELAND, REPUBLIC OF, self.message=Delivery attempted; recipient not home, self.tag=AttemptFail, self.zip=(null)>",
    "<AftershipCheckpoint: self.createTime=2015-01-02 13:46:57 +0000, self.slug=dhl, self.checkpointTime=2015-01-02T13:30:00, self.city=(null), self.state=(null), self.countryCode=(null), self.countryName=SHANNON - IRELAND, REPUBLIC OF, self.message=Delivered - Signed for by : T HEHIR JODYS, self.tag=Delivered, self.zip=(null)>",
    "<AftershipCheckpoint: self.createTime=2015-01-02 17:08:06 +0000, self.slug=dhl, self.checkpointTime=2015-01-02T13:30:00, self.city=SHANNON, self.state=(null), self.countryCode=(null), self.countryName=SHANNON - IRELAND, REPUBLIC OF, self.message=Delivered - Signed for by, self.tag=Delivered, self.zip=(null)>"

Interesting, I don't observe such bug in your iOS app.

**Comment by andrew8712** [comment]
Sorry, forgot about it:
9523883110

**Comment by andrew8712** [comment]
slug = dhl

**Comment by dg3feiko** [comment]
sorry, I want the api key of that developer as well

**Comment by andrew8712** [comment]
For obvious reason I can't post it here, can you please give me your email address?

**Comment by dg3feiko** [comment]
@andrew8712 please contact my office email:  feiko@aftership.net

**Comment by andrew8712** [comment]
Any updates? I have sent my API key to you few days ago.

**Comment by andrew8712** [comment]
Hello? Any updates after 2 weeks?

**Comment by dg3feiko** [comment]
@andrew8712 

We inspected the tracking, the result we got is ok. 
Are you still getting the same duplicated result currently?

**Comment by andrew8712** [comment]
Just tested - seems fixed, thanks.
